#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "open3"
require "optparse"
require "pathname"
require "set"

ROOT_DIR = File.expand_path("..", __dir__)
BOOK_TEX = "book.tex"
FLS_FILE = "book.fls"

# File extensions for LaTeX intermediate/temporary files
TEMP_EXTENSIONS = Set.new(%w[
  .aux .log .toc .lof .lot .out .fls .fdb_latexmk .synctex .xdv .dvi
  .bcf .blg .bbl .ist .glo .gls .glg .idx .ind .ilg .thm .nav .snm .vrb .ent
  .rel .latex_color .plmath_history .lst .tmp .bak .ps .eps
]).freeze

# Compound extensions or endings that signify temporary files
TEMP_ENDINGS = %w[
  .run.xml .synctex.gz .synctex(busy) .bbl.bak .bbl-SAVE-ERROR .bcf-SAVE-ERROR
].freeze

# Known figure source extensions to keep when an image is accessed
FIGURE_SOURCE_EXTENSIONS = %w[
  .ipe .ipe6 .ipe7 .fig .xfig .svg .gnuplot .gp .ai .dia
  .png .jpg .jpeg .gif .xml .tex .asy .dot .gv
].freeze

# Project-level infrastructure files to always preserve
PROTECTED_PROJECT_FILES = Set.new(%w[
  book.tex prefix.tex bookit put_on_web
  fixing_fragment.md test_all_chaps.rb
]).freeze

# Directories containing project tools or assets to keep intact
PROTECTED_ROOT_DIRS = Set.new(%w[
  tools scripts shared .git
]).freeze

class LatexCleaner
  attr_reader :options, :accessed_files, :useful_fragments, :figure_sources,
              :outdated_ipe_files, :removed_temp_files, :removed_junk_dirs,
              :removed_frag_symlinks, :removed_empty_dirs, :removed_generated_pdfs,
              :removed_outdated_ipe_files, :unsure_files

  def initialize(options = {})
    @options = options
    @root = Pathname.new(ROOT_DIR)
    @accessed_files = Set.new
    @useful_fragments = Set.new
    @figure_sources = Set.new
    @outdated_ipe_files = Set.new

    @removed_temp_files = []
    @removed_junk_dirs = []
    @removed_frag_symlinks = []
    @removed_empty_dirs = []
    @removed_generated_pdfs = []
    @removed_outdated_ipe_files = []
    @unsure_files = Hash.new { |h, k| h[k] = [] }
  end

  def run
    puts "=== LaTeX Repository Cleanup Tool ==="
    puts "Root directory: #{@root}"
    puts "Mode: #{options[:dry_run] ? 'DRY-RUN (no files will be deleted)' : 'ACTIVE (files will be deleted)'}"
    puts "Delete generated PDFs: #{options[:delete_generated_pdfs] ? 'YES' : 'NO'}"
    puts "======================================"

    fls_path = File.join(ROOT_DIR, FLS_FILE)
    if !options[:skip_compile] || !File.exist?(fls_path)
      compile_book_and_record_access
    else
      puts "\nReusing existing #{FLS_FILE} (--skip-compile specified)."
    end

    parse_fls_file
    discover_figure_sources
    find_outdated_ipe_files
    process_repository
    clean_root_temp_files unless options[:dry_run] || options[:keep_fls]
    clean_empty_dirs unless options[:dry_run]

    print_report
  end

  private

  def compile_book_and_record_access
    puts "\n[1/4] Running XeLaTeX with -recorder on #{BOOK_TEX}..."
    cmd = ["xelatex", "-interaction=nonstopmode", "-recorder", BOOK_TEX]
    stdout, stderr, status = Open3.capture3(*cmd, chdir: ROOT_DIR)

    unless status.success?
      warn "Warning: xelatex exited with code #{status.exitstatus}. Proceeding with generated .fls..."
    end
    puts "XeLaTeX compilation complete. Generated #{FLS_FILE}."
  end

  def parse_fls_file
    puts "\n[2/4] Analyzing accessed files from #{FLS_FILE}..."
    fls_path = File.join(ROOT_DIR, FLS_FILE)
    unless File.exist?(fls_path)
      warn "Error: #{FLS_FILE} not found."
      exit 1
    end

    File.foreach(fls_path) do |line|
      if line =~ /^INPUT\s+(.+)$/
        raw_path = $1.strip
        rel = normalize_to_repo_rel(raw_path)
        @accessed_files << rel if rel
      elsif line =~ /^OUTPUT\s+(.+)$/
        raw_path = $1.strip
        rel = normalize_to_repo_rel(raw_path)
        if rel && rel.start_with?("fragment/") && rel.end_with?(".tex")
          @useful_fragments << rel
        end
      end
    end

    puts "Recorded #{@accessed_files.size} accessed input files in the repository."
    puts "Recorded #{@useful_fragments.size} active fragment definitions generated by book.tex."
  end

  def normalize_to_repo_rel(path_str)
    pn = Pathname.new(path_str)
    if pn.absolute?
      return nil unless path_str.start_with?(@root.to_s)
      pn = pn.relative_path_from(@root)
    end
    rel = pn.cleanpath.to_s
    return nil if rel.start_with?("/") || rel.start_with?("..")
    rel
  end

  def discover_figure_sources
    puts "\n[3/4] Discovering original figure sources for accessed figures..."
    @accessed_files.each do |file_rel|
      ext = File.extname(file_rel).downcase
      next unless %w[.pdf .eps .png .jpg .jpeg .gif].include?(ext)

      dir = File.dirname(file_rel)
      base = File.basename(file_rel, ".*")

      # 1. Matching basename with source extension in the same directory
      FIGURE_SOURCE_EXTENSIONS.each do |src_ext|
        cand = File.join(dir, "#{base}#{src_ext}")
        if File.exist?(File.join(ROOT_DIR, cand))
          @figure_sources << Pathname.new(cand).cleanpath.to_s
        end
      end

      # 2. Multi-page or component subdirectory with the same base name (e.g. figs/vertical/)
      sub_dir = File.join(ROOT_DIR, dir, base)
      if Dir.exist?(sub_dir)
        Dir.glob(File.join(sub_dir, "**/*")).each do |sf|
          if File.file?(sf)
            rel = Pathname.new(sf).relative_path_from(@root).cleanpath.to_s
            @figure_sources << rel
          end
        end
      end

      # 3. Scripts referencing the figure basename in the figs directory
      figs_dir = File.join(ROOT_DIR, dir)
      Dir.glob(File.join(figs_dir, "*.gnuplot")).each do |gp|
        content = File.read(gp) rescue ""
        if content.include?(base)
          @figure_sources << Pathname.new(gp).relative_path_from(@root).cleanpath.to_s
        end
      end
    end

    # Keep all makefiles and scripts in figs directories
    Dir.glob(File.join(ROOT_DIR, "**/figs/*")).each do |f|
      base = File.basename(f)
      if %w[makefile Makefile animate_pdf_to_gif generate_animation].include?(base) || base.end_with?(".gnuplot")
        @figure_sources << Pathname.new(f).relative_path_from(@root).cleanpath.to_s
      end
    end

    # Keep figure generator scripts in chapter tools/
    Dir.glob(File.join(ROOT_DIR, "**/tools/generate_figure*")).each do |f|
      @figure_sources << Pathname.new(f).relative_path_from(@root).cleanpath.to_s
    end

    puts "Identified #{@figure_sources.size} figure sources/scripts to preserve."
  end

  def find_outdated_ipe_files
    ipe_pattern = File.join(ROOT_DIR, "**/*.{ipe,ipe6,ipe7}")
    by_dir_and_base = Hash.new { |h, k| h[k] = [] }

    Dir.glob(ipe_pattern, File::FNM_DOTMATCH).each do |file|
      rel = Pathname.new(file).relative_path_from(@root).cleanpath.to_s
      parts = rel.split("/")
      next if parts.include?(".git") || parts.include?(".bws") || parts.include?("junk")

      dir = File.dirname(file)
      base = File.basename(file).sub(/\.ipe\d*$/, "")
      by_dir_and_base[[dir, base]] << file
    end

    by_dir_and_base.each do |_key, files|
      next if files.size <= 1

      ranked = files.map do |f|
        ext = File.extname(f).downcase
        rank = case ext
               when ".ipe" then 3
               when ".ipe7" then 2
               when ".ipe6" then 1
               else 0
               end
        mtime = File.mtime(f).to_i rescue 0
        { file: f, rank: rank, mtime: mtime }
      end

      ranked.sort_by! { |item| [-item[:rank], -item[:mtime]] }

      # The first item is the newest; all others in this directory sharing the base name are outdated
      ranked[1..-1].each do |older|
        rel = Pathname.new(older[:file]).relative_path_from(@root).cleanpath.to_s
        @outdated_ipe_files << rel
      end
    end

    puts "Identified #{@outdated_ipe_files.size} outdated Ipe drawing versions with newer copies in the same directory."
  end

  def process_repository
    puts "\n[4/4] Scanning repository: cleaning temporary files and identifying unsure files..."

    # Pass 1: Find and remove fragment symlinks and junk/auto directories
    Dir.glob(File.join(ROOT_DIR, "**/*"), File::FNM_DOTMATCH).each do |entry|
      base = File.basename(entry)
      next if base == "." || base == ".."

      rel = Pathname.new(entry).relative_path_from(@root).cleanpath.to_s
      parts = rel.split("/")
      next if parts.any? { |p| PROTECTED_ROOT_DIRS.include?(p) }

      if File.symlink?(entry)
        target = File.readlink(entry) rescue ""
        if base == "fragment" || target.include?("fragment")
          @removed_frag_symlinks << rel
          FileUtils.rm(entry) unless options[:dry_run]
          next
        end
      elsif File.directory?(entry)
        if %w[junk auto .auctex-auto .bws].include?(base)
          @removed_junk_dirs << rel
          FileUtils.rm_rf(entry) unless options[:dry_run]
          next
        end
      end
    end

    # Pass 2: Process individual files and remaining symlinks
    Dir.glob(File.join(ROOT_DIR, "**/*"), File::FNM_DOTMATCH).each do |entry|
      base = File.basename(entry)
      next if base == "." || base == ".."

      rel = Pathname.new(entry).relative_path_from(@root).cleanpath.to_s
      parts = rel.split("/")

      # Ignore anything in root protected directories (.git, tools, scripts, etc.)
      next if PROTECTED_ROOT_DIRS.include?(parts.first)
      next if parts.include?(".git")

      # Ignore anything inside refs/ directories - always preserved!
      next if parts.include?("refs")

      # Already handled if under a removed junk, auto, or .bws directory
      next if parts.any? { |p| %w[junk auto .auctex-auto .bws].include?(p) }

      # Handle symbolic links
      if File.symlink?(entry)
        target = File.readlink(entry) rescue ""
        if base == "fragment" || target.include?("fragment")
          @removed_frag_symlinks << rel unless @removed_frag_symlinks.include?(rel)
          FileUtils.rm(entry) unless options[:dry_run]
          next
        end

        # Emacs lock symlink (.#filename)
        if base.start_with?(".#")
          @removed_temp_files << rel
          FileUtils.rm(entry) unless options[:dry_run]
          next
        end
      end

      # Skip directories (only files and unhandled symlinks proceed past here)
      next if File.directory?(entry) && !File.symlink?(entry)

      # Check if this is a temporary file (.aux, .log, .bbl, .bcf, etc.)
      if temporary_file?(rel, entry)
        @removed_temp_files << rel
        FileUtils.rm_f(entry) unless options[:dry_run]
        next
      end

      # Outdated Ipe file check: delete only if a newer version exists in the directory
      if @outdated_ipe_files.include?(rel)
        @removed_outdated_ipe_files << rel
        FileUtils.rm_f(entry) unless options[:dry_run]
        next
      end

      # Generated PDF files handling
      if rel.end_with?(".pdf")
        if rel == "book.pdf"
          if options[:delete_book_pdf]
            @removed_generated_pdfs << rel
            FileUtils.rm_f(entry) unless options[:dry_run]
            next
          else
            next # Preserve book.pdf by default
          end
        end

        # Figure PDFs accessed by book.tex are preserved
        if @accessed_files.include?(rel)
          next
        end

        # Other PDF files are generated PDFs and can be deleted
        if options[:delete_generated_pdfs]
          @removed_generated_pdfs << rel
          FileUtils.rm_f(entry) unless options[:dry_run]
          next
        else
          if rel =~ %r{^[0-9]{2}_[^/]+/([^/]+)\.pdf$}
            @unsure_files["Standalone chapter PDFs"] << rel
          else
            @unsure_files["Other unreferenced PDF files"] << rel
          end
          next
        end
      end

      # Check if known useful
      next if PROTECTED_PROJECT_FILES.include?(rel)
      next if @accessed_files.include?(rel)
      next if @useful_fragments.include?(rel)
      next if @figure_sources.include?(rel)

      # Otherwise, categorize as UNSURE
      classify_unsure_file(rel, entry)
    end
  end

  def temporary_file?(rel, full_path)
    ext = File.extname(rel).downcase
    base = File.basename(rel)

    # Standard temporary extension
    return true if TEMP_EXTENSIONS.include?(ext)

    # Compound temp endings
    return true if TEMP_ENDINGS.any? { |ending| rel.end_with?(ending) }

    # Pattern based temporary files
    return true if %w[.latex_color .plmath_history .lst .renumber_log.json .config_latex].include?(base)
    return true if base =~ /^err_/
    return true if base =~ /^\.#/
    return true if base.end_with?("~")
    return true if base == "log.txt"
    return true if base == "frag_probe.tmp"
    return true if base =~ /tex\}\{\}$/

    false
  end

  def classify_unsure_file(rel, full_path)
    ext = File.extname(rel).downcase
    base = File.basename(rel)

    if File.symlink?(full_path)
      @unsure_files["Broken or stray symlinks"] << rel
    elsif rel.start_with?("old_stuff/")
      @unsure_files["Archived / backup files (old_stuff/)"] << rel
    elsif rel.start_with?("fragment/")
      @unsure_files["Stale fragment definitions (not output by book.tex)"] << rel
    elsif ext == ".tex"
      @unsure_files["Unreferenced TeX source files"] << rel
    elsif %w[.ipe .ipe6 .ipe7].include?(ext)
      @unsure_files["Preserved Ipe drawing sources (unreferenced in book.tex)"] << rel
    elsif %w[.fig .xfig .svg .eps .ps .gif].include?(ext)
      @unsure_files["Unreferenced figure and drawing files"] << rel
    elsif ext == ".bib"
      @unsure_files["Standalone chapter bibliography files (.bib)"] << rel
    else
      @unsure_files["Other unclassified / stray files"] << rel
    end
  end

  def clean_root_temp_files
    # Clean temporary files produced by the recorder run on book.tex
    root_temp_files = %w[
      book.aux book.log book.out book.idx book.toc book.bcf book.run.xml
      frag_probe.tmp
    ]
    root_temp_files << FLS_FILE unless options[:keep_fls]

    root_temp_files.each do |f|
      path = File.join(ROOT_DIR, f)
      if File.exist?(path)
        @removed_temp_files << f unless @removed_temp_files.include?(f)
        FileUtils.rm_f(path)
      end
    end
  end

  def clean_empty_dirs
    # Prune empty directories that may have been left behind
    Dir.glob(File.join(ROOT_DIR, "**/*")).sort.reverse_each do |dir|
      next unless File.directory?(dir)
      rel = Pathname.new(dir).relative_path_from(@root).cleanpath.to_s
      parts = rel.split("/")
      next if parts.any? { |p| PROTECTED_ROOT_DIRS.include?(p) || p == "refs" }

      if (Dir.entries(dir) - %w[. ..]).empty?
        @removed_empty_dirs << rel
        Dir.rmdir(dir) rescue nil
      end
    end
  end

  def print_report
    puts "\n" + "=" * 60
    puts "                   CLEANUP REPORT"
    puts "=" * 60

    puts "\nActions performed#{options[:dry_run] ? ' (DRY RUN)' : ''}:"
    puts format("  - Junk, AUCTeX & .bws dirs removed:    %4d", @removed_junk_dirs.size)
    puts format("  - LaTeX temporary files removed:        %4d", @removed_temp_files.size)
    puts format("  - Fragment symbolic links removed:      %4d", @removed_frag_symlinks.size)
    puts format("  - Outdated Ipe drawing files removed:   %4d", @removed_outdated_ipe_files.size)
    puts format("  - Generated PDF files removed:          %4d", @removed_generated_pdfs.size)
    puts format("  - Empty leftover directories pruned:    %4d", @removed_empty_dirs.size)

    if @removed_frag_symlinks.any?
      puts "\nRemoved Fragment Symlinks:"
      @removed_frag_symlinks.each { |s| puts "  - #{s}" }
    end

    if @removed_outdated_ipe_files.any?
      puts "\nRemoved Outdated Ipe Files (newer version present):"
      @removed_outdated_ipe_files.sort.each { |f| puts "  - #{f}" }
    end

    total_unsure = @unsure_files.values.map(&:size).sum
    puts "\n" + "=" * 60
    puts format("UNSURE / UNREFERENCED FILES FOUND: %d", total_unsure)
    puts "These files are NOT temporary LaTeX files, were NOT accessed"
    puts "during the compilation of book.tex, are NOT figure sources, and"
    puts "are NOT in refs/. Review them to decide if they should be kept."
    puts "=" * 60

    @unsure_files.keys.sort.each do |category|
      files = @unsure_files[category].sort
      puts "\n### #{category} (#{files.size}):"
      files.each do |f|
        puts "  #{f}"
      end
    end

    puts "\n" + "=" * 60
    puts "Summary:"
    puts "  Total files accessed by book.tex: #{@accessed_files.size}"
    puts "  Total figure sources preserved:   #{@figure_sources.size}"
    puts "  Total unsure files to review:     #{total_unsure}"
    puts "=" * 60
  end
end

def parse_options
  options = {
    dry_run: false,
    skip_compile: false,
    delete_generated_pdfs: true,
    delete_book_pdf: false,
    keep_fls: false
  }

  OptionParser.new do |opts|
    opts.banner = "Usage: #{$PROGRAM_NAME} [options]"

    opts.on("-n", "--dry-run", "Preview files to be removed without deleting them") do
      options[:dry_run] = true
    end

    opts.on("-s", "--skip-compile", "Skip xelatex compilation and reuse existing book.fls") do
      options[:skip_compile] = true
    end

    opts.on("--keep-generated-pdfs", "Do not delete generated PDF files (chapter PDFs, etc.)") do
      options[:delete_generated_pdfs] = false
    end

    opts.on("--delete-book-pdf", "Also delete the master book.pdf") do
      options[:delete_book_pdf] = true
    end

    opts.on("--keep-fls", "Keep book.fls recorder file after execution") do
      options[:keep_fls] = true
    end

    opts.on("-h", "--help", "Show this help message") do
      puts opts
      exit 0
    end
  end.parse!

  options
end

if __FILE__ == $PROGRAM_NAME
  options = parse_options
  cleaner = LatexCleaner.new(options)
  cleaner.run
end
